blocklistConfig.json
**Host link:** https://raw.githubusercontent.com/bongochong/CombinedPrivacyBlockLists/master/newhosts-final.hosts
**Source:** [CombinedPrivacyBlockLists](https://github.com/bongochong/CombinedPrivacyBlockLists) by @bongochong
**License:** [CPAL-1.0](https://github.com/bongochong/CombinedPrivacyBlockLists/blob/master/LICENSE)
**Description:** Ad & malware-blocking hosts files, IP blocklists, PAC filters, and ABP / uBO subscriptions, all merged, sorted and de-duped from multiple reputable sources, along with bongochong's own research. It block malicious and harmfully deceptive content, like advertising, tracking, telemetry, scam, and malware servers. The lists **do not** block porn, social media, or so-called "fake news" domains, except for the advertising, tracking, telemetry, scam, and …
=> Update blocklistConfig.json with CPBL hosts

blocklistConfig.json
I hope this is OK, but it would be neat to have the less aggressive variant of my hosts file available through rethink. It's a little bit less aggressive and useful as a list for smart TVs and similar devices which require extra leniency. I have differentiated between the two lists in blocklistConfig.json as well.
=> Addition of Light/Mini Variant of my Hosts File

blocklistConfig.json
Malicious URL blocklist automatically generated by scanning various public URL sources using the Safe Browsing API from Google
=> Add Inversion domains feed

blocklistConfig.json
Used "**Persian Blocker**" instead of "PersianBlocker" to _hopefully_ [resolve ambiguity](https://github.com/celzero/rethink-app/issues/569#issuecomment-1252449075) as mentioned by @ignoramous.
(So users will perceive it "Persian _ad/tracker_ Blocker")
By the way the README instructions lack the `"pack": []` part.
=> Add PersianBlocker list

config.json
So badd boyz host was last updated 6 months ago and with that, some URLs may be broken. Ultimate host blacklist tries to remove those and thus saving about 100 domains here. Also switched it to domains from hosts. More info at the github https://github.com/Ultimate-Hosts-Blacklist/BaddBoyzHosts
=> Switch Badd Boyz Hosts to Domains & Clean

config.json
A small list that is included with nextdns and it should be included here in my opinion
=> Add Nextdns Disguised Third-Party Tracker List

config.json
These changes are extremely tiny and are only for changing to 0.0.0.0 from 127.0.0.1 for someonewhocares.org and removing the # adware (for example) next to each entry in the no track list
=> Minor blocklist link changes

config.json
Maybe add the rest of hagezi’s adblocking blocklists to replace some more dead energized lists
=> Replace Energized Blu Go & Basic with Hagezi multi & light

config.json
did not realize it was called normal and not light. Changed it now to fix that typo
=> config.json: typo

config.json
Messengers might give the impression it is blocking all messenger services but that isn’t true here. The ShadowWhisperer list might not work well here as messenger (facebook) and chat boxes on websites are different things. Maybe a different location for ShadowWhisperer’s chat list would be better suited
=> Rename Threats to Threat Intelligence Feeds for Hagezi

config.json
Marco Acorte’s list is already included in Hagezi’s threat intelligence so keeping it alongside is redundant
=> config: typo and rmv Marco Acorte’s list because redundant

config.json
Changes :
- Remove double DL (the .fr list is integrated in the main link)
- Move RFD into Security category
- Assign correct packs
=> Get RedFlagDomains its own entry

config.json
- Move antispam-it to bundle with EasyList Italy
- Move ShadowWhisperer Shock Blocklist to its own NSFL blocklist
- Move HexxiumCreations and HostsVN Extension to Threats and IOCs
- Move ShadowWhisperer URLShortner to create the URL Shortners bundle
- Move ShadowWhisperer Bloat to its own due to the breakage potential
- Move TBLP Scamware to its own
- Delete chadmayfield [archived](https://github.com/chadmayfield/my-pihole-blocklists) porn list
=> Split and rearrange bundles

download.py
HostsVN fails because of the missing leading `*.` (the HVN format is `*domain`, contrary to the tracked `*.domain` `wildcard` format) in the domains of that list
=> Fix download script regex for wildcards

config.json
Found at https://hblock.molinero.dev/ or https://github.com/hectorm/hblock . 
NextDNS just added the blocklist to their lists so why not add it here as well!
Maybe you can find a better fitting name however. I couldn’t think of anything
=> Add hBlock blocklist

node.Dockerfile
The correct way to specify a runner is through AS and not as . I’m unaware of any consequences of using the current way but it helps distinguish from arguments easier when capitalized
=> node.dockerfile: capitalize as

config.json
I was doing some thinking and maybe adguard cname blocklist should not be with adguard sdns since there is a higher chance for false positives and you mentioned in the past that serverless dns already uncloaks cnames anyways. So it seems like a good idea to remove this list from sdns
=> config: rmv Adguard combined disguised trackers

config.json
Fixes source for Oisd as it was updated again.
removed typo squatting for ShadowWhisperer as it has not been updated since July of 2022 and cbuijs accomplishes everything that it doesn’t from the looks of the size of domains. Also changed source of auto discovery because the cbuijs one includes that source and more
=> Update oisd sources, change autodiscovery

config.json
https://cert.pl/en/warning-list/
=> config: Switch hole.cert.pl to v2 list and update categories

config.json
This is blocklist for blocking mainly unsafe websites filled with malware downloads mostly related to piracy (but this blocklist is \*\*NOT\*\* intended to be used as "Anti piracy blocklist", this blocklist blocks just the dangerous domains), also it blocks domains of some (crappy) PUP softwares (thats why the "Spyware" pack has level "1", not "0" here, because some people with weird taste of software could use it and then complain, that it doesn‘t work right).
Reasons for blocking these domains can be found here: https://fmhy.net/unsafesites
Website of the blocklist: https://windowsaurora.github.io/FMHYFilterlist/site
=> Add FMHY Unsafe sites Filterlist
